"""Pydantic models for agent structured outputs."""

from datetime import datetime, timezone
from typing import Literal

from pydantic import BaseModel, Field


class KPIItem(BaseModel):
    """Key performance indicator with bilingual label and brief assessment."""

    name: str = Field(description="Bilingual label, e.g. P/E Ratio（市盈率）")
    value: str
    assessment: str = Field(
        description="Meaningful 2-3 sentence evaluation with investor implication.",
    )


class EarningsTableRow(BaseModel):
    """Single row in the bilingual earnings summary table."""

    metric: str = Field(description="Bilingual metric name, e.g. Revenue（營收）")
    period: str = Field(default="", description="Reporting period label, e.g. FY2025")
    actual: str
    consensus: str = Field(description="Market consensus or '數據不可用'")
    yoy_growth: str
    result: Literal["Beat", "Miss", "Inline", "N/A"] = "N/A"
    commentary: str = Field(
        description="Detailed row analysis, 2-3 sentences explaining trend and implication.",
    )


class SegmentItem(BaseModel):
    """Business segment performance detail."""

    segment_name: str
    performance_summary: str = Field(description="At least 3 sentences.")
    ai_relevance: str = Field(description="AI-related commentary, at least 2 sentences.")
    growth_outlook: str = Field(description="Forward outlook, at least 2 sentences.")


class GuidanceComparisonItem(BaseModel):
    """Company guidance vs market expectation."""

    metric: str
    company_guidance: str
    market_expectation: str
    gap_analysis: str = Field(description="At least 2 sentences.")


class RiskFactorDetail(BaseModel):
    """Structured risk factor per Step 1 requirements."""

    title: str
    description: str = Field(
        description="Detailed risk description, minimum 3 sentences with context and mechanism.",
    )
    potential_impact: str = Field(
        description="Specific impact on revenue, margins, valuation or stock price, 2-3 sentences.",
    )
    impact_level: Literal["高", "中高", "中", "中低", "低"]
    monitoring_signal: str = Field(
        default="",
        description="What investors should monitor as early warning signals.",
    )


class PriceActionLevel(BaseModel):
    """Explicit price level guidance."""

    label: str
    price_range: str = Field(description="Concrete numeric range, e.g. 180-195 USD")
    rationale: str = Field(description="Why this level matters, 2+ sentences.")


class InvestmentSummaryDetail(BaseModel):
    """Detailed investment recommendation block."""

    overall_view: Literal["Bullish", "Neutral", "Bearish"]
    short_term_outlook: str = Field(description="Detailed 1-3 month outlook, 5+ sentences.")
    medium_long_term_outlook: str = Field(description="Detailed 6-12 month outlook, 5+ sentences.")
    current_price_analysis: str = Field(description="Detailed price reasonableness, 5+ sentences.")
    suggested_buy_price: str = Field(description="Concrete buy zone, e.g. 180-195 USD")
    take_profit_price: str = Field(description="Concrete take-profit zone, e.g. 250-270 USD")
    target_price_range: str = Field(description="Concrete target range, e.g. 250-280 USD")
    stop_loss_price: str = Field(default="", description="Optional stop-loss zone.")
    target_price_rationale: str = Field(description="Detailed rationale, 6+ sentences.")
    buy_conditions: str = Field(description="At least 4 specific buy triggers.")
    hold_conditions: str = Field(description="At least 3 specific hold triggers.")
    sell_conditions: str = Field(description="At least 3 specific sell triggers.")
    investment_strategy: str = Field(description="Comprehensive strategy, 10+ sentences.")
    price_action_levels: list[PriceActionLevel] = Field(default_factory=list)
    recommendation: Literal["Strong Buy", "Buy", "Hold", "Sell", "Strong Sell"]
    confidence: Literal["High", "Medium", "Low"]


class FundamentalReport(BaseModel):
    """Structured fundamental analysis report generated by Grok."""

    ticker: str
    company_name: str
    analysis_date: str
    data_updated_at: str
    realtime_data_note: str
    generated_at: str = Field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat(),
    )

    executive_summary: str = Field(description="Detailed executive summary, 10-15 sentences.")
    business_overview: str = Field(description="Detailed company overview, 8-12 sentences.")
    financial_analysis: str = Field(description="Deep financial analysis, 12+ sentences.")
    earnings_summary: str = Field(description="Detailed earnings narrative, 6+ sentences.")
    earnings_table: list[EarningsTableRow] = Field(default_factory=list)
    key_kpis: list[KPIItem] = Field(default_factory=list)
    segment_breakdown: list[SegmentItem] = Field(default_factory=list)
    segment_performance: str
    guidance_comparison: list[GuidanceComparisonItem] = Field(default_factory=list)
    guidance_vs_expectations: str
    valuation_assessment: str
    competitive_moat: str

    risk_factors_detail: list[RiskFactorDetail] = Field(default_factory=list)
    risk_factors: list[str] = Field(default_factory=list)
    investment_detail: InvestmentSummaryDetail

    overall_view: Literal["Bullish", "Neutral", "Bearish"]
    short_term_outlook: str
    medium_long_term_outlook: str
    current_price_analysis: str
    suggested_buy_price: str
    take_profit_price: str
    target_price_range: str
    target_price_rationale: str = ""
    stop_loss_price: str = ""
    buy_conditions: str = ""
    hold_conditions: str = ""
    sell_conditions: str = ""
    investment_strategy: str
    investment_outlook: str
    price_action_levels: list[PriceActionLevel] = Field(default_factory=list)
    recommendation: Literal["Strong Buy", "Buy", "Hold", "Sell", "Strong Sell"]
    confidence: Literal["High", "Medium", "Low"]

    report_markdown: str
    html_report: str = ""


class DeepCheckDimension(BaseModel):
    """Single dimension analysis block for Step 2 deep pre-buy check."""

    dimension_id: int = Field(ge=1, le=8)
    title: str
    analysis: str = Field(
        description="Detailed analysis, minimum 150-250 Chinese characters.",
    )
    key_findings: list[str] = Field(default_factory=list)
    risk_flags: list[str] = Field(default_factory=list)
    verdict: str = Field(default="中性", description="Dimension verdict, e.g. 正面/中性/負面")


class DeepCheckUserProfile(BaseModel):
    """User personal context for Step 2 personal fit analysis."""

    available_capital: str = ""
    risk_tolerance: str = ""
    investment_horizon: str = ""
    portfolio_concentration: str = Field(
        default="",
        description="Existing portfolio concentration context if provided.",
    )


class DeepCheckReport(BaseModel):
    """Structured deep pre-buy check report (Step 2)."""

    ticker: str
    company_name: str
    analysis_date: str
    data_updated_at: str
    realtime_data_note: str
    user_profile: DeepCheckUserProfile = Field(default_factory=DeepCheckUserProfile)
    generated_at: str = Field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat(),
    )

    dimensions: list[DeepCheckDimension] = Field(
        default_factory=list,
        description="Must contain exactly eight dimension analyses (id 1-8).",
    )

    management_quality: str = Field(
        default="",
        description="Section 1: Management quality and execution.",
    )
    moat_and_ai_leadership: str = Field(
        default="",
        description="Section 2: Moat and AI leadership.",
    )
    macro_geopolitics: str = Field(
        default="",
        description="Section 3: Macro and geopolitical environment.",
    )
    market_sentiment: str = Field(
        default="",
        description="Section 4: Market sentiment and fund flows.",
    )
    technical_timing: str = Field(
        default="",
        description="Section 5: Technical analysis and entry timing.",
    )
    valuation_fairness: str = Field(
        default="",
        description="Section 6: Valuation fairness.",
    )
    catalysts_and_black_swans: str = Field(
        default="",
        description="Section 7: Catalysts and black swan risks.",
    )
    personal_fit: str = Field(
        default="",
        description="Section 8: Personal profile fit.",
    )

    overall_rating: Literal["Strong Buy", "Buy", "Neutral", "Avoid"]
    suggested_position_size: str = Field(
        description="Suggested portfolio allocation percentage.",
    )
    entry_price_range: str
    stop_loss: str
    main_buy_reasons: list[str] = Field(default_factory=list)
    max_risk: str
    final_recommendation: str = Field(
        description="Is it suitable for the user and how to scale in.",
    )

    report_markdown: str


class TechnicalSection(BaseModel):
    """Single section for Step 3 technical analysis report."""

    section_id: int = Field(ge=1, le=6)
    title: str
    analysis: str = Field(description="Detailed section analysis.")
    key_points: list[str] = Field(default_factory=list)


class TechnicalAnalysisReport(BaseModel):
    """Structured technical analysis report (Step 3)."""

    ticker: str
    company_name: str
    analysis_date: str
    data_updated_at: str
    realtime_data_note: str
    generated_at: str = Field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat(),
    )

    sections: list[TechnicalSection] = Field(default_factory=list)

    overall_summary: str = Field(description="Section 1: Overall technical summary.")
    key_indicators_analysis: str = Field(description="Section 2: Key indicators analysis.")
    chart_patterns_and_levels: str = Field(description="Section 3: Chart patterns and levels.")
    technical_conclusion: str = Field(description="Section 4: Technical conclusion.")
    entry_strategy: str = Field(description="Section 5: Entry strategy recommendation.")
    risk_warnings: str = Field(description="Section 6: Risk warnings.")

    technical_rating: Literal["強烈看多", "看多", "中性", "看空", "強烈看空"]
    suitable_for_entry: Literal["是", "否", "觀望"]
    entry_price_range: str
    stop_loss: str
    take_profit_1: str
    take_profit_2: str
    position_size: str

    report_markdown: str